const express = require('express');
const router = express.Router();
const PDFDocument = require('pdfkit');
const db = require('./database');
const { authenticateToken } = require('./auth');

// GET /api/download/:itineraryId
router.get('/:itineraryId', authenticateToken, (req, res) => {
  try {
    const itinerary = db.get('itineraries').find({ id: req.params.itineraryId, userId: req.user.id }).value();
    if (!itinerary) return res.status(404).json({ error: 'Itinerary not found.' });

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const filename = `WayEase_${itinerary.city}_${itinerary.days}Days.pdf`;
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    doc.pipe(res);

    // Header
    doc.rect(0, 0, doc.page.width, 110).fill('#87cfbe');
    doc.fillColor('white').font('Helvetica-Bold').fontSize(28).text('WayEase', 50, 28);
    doc.fontSize(12).font('Helvetica').text('Your Personal Travel Planner', 50, 62);

    // Title
    doc.fillColor('#1a202c').font('Helvetica-Bold').fontSize(22).text(itinerary.title || `${itinerary.city} Adventure`, 50, 130, { align: 'center' });

    // Meta
    doc.fontSize(11).fillColor('#4a5568').font('Helvetica');
    doc.text(`Location: ${itinerary.city}`, 50, 168);
    doc.text(`Duration: ${itinerary.days} Day${itinerary.days > 1 ? 's' : ''}`, 220, 168);
    if (itinerary.estimatedBudget) doc.text(`Budget: ${itinerary.estimatedBudget}`, 360, 168);

    if (itinerary.summary) {
      doc.moveDown(2).font('Helvetica-Oblique').fontSize(11).fillColor('#4a5568').text(itinerary.summary, 50, doc.y, { align: 'justify', lineGap: 4 });
    }
    if (itinerary.preferences?.length > 0) {
      doc.moveDown(0.8).font('Helvetica-Bold').fontSize(10).fillColor('#87cfbe').text('INTERESTS: ', { continued: true })
         .font('Helvetica').fillColor('#4a5568').text(itinerary.preferences.join('  •  '));
    }

    doc.moveDown(0.5).moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).strokeColor('#e2e8f0').stroke();

    // Days
    (itinerary.itinerary || []).forEach(dayPlan => {
      doc.moveDown(1.5);
      const dayY = doc.y;
      doc.rect(50, dayY, doc.page.width - 100, 30).fill('#87cfbe');
      doc.fillColor('white').font('Helvetica-Bold').fontSize(13).text(`DAY ${dayPlan.day}  —  ${dayPlan.theme || ''}`, 60, dayY + 8);
      doc.moveDown(1.5);

      (dayPlan.activities || []).forEach((act, i) => {
        if (doc.y > doc.page.height - 160) doc.addPage();
        doc.fillColor('#1a202c').font('Helvetica-Bold').fontSize(12).text(`${i + 1}. ${act.place}  |  ${act.time}`, 50, doc.y);
        doc.fillColor('#4a5568').font('Helvetica-Oblique').fontSize(10).text(act.activity, 50, doc.y + 2);
        if (act.description) doc.fillColor('#718096').font('Helvetica').fontSize(10).text(act.description, 60, doc.y + 4, { width: doc.page.width - 120 });
        if (act.tips) doc.moveDown(0.3).fillColor('#87cfbe').font('Helvetica-Bold').fontSize(9).text('Tip: ', 60, doc.y, { continued: true }).font('Helvetica').fillColor('#4a5568').text(act.tips);
        doc.moveDown(0.8).moveTo(60, doc.y).lineTo(doc.page.width - 60, doc.y).strokeColor('#f0f4f8').lineWidth(0.5).stroke();
        doc.moveDown(0.4);
      });
    });

    // Tips
    if (itinerary.tips?.length > 0) {
      if (doc.y > doc.page.height - 200) doc.addPage();
      doc.moveDown(1.5).font('Helvetica-Bold').fontSize(13).fillColor('#b7791f').text('TRAVEL TIPS');
      doc.moveDown(0.8);
      itinerary.tips.forEach((tip, i) => {
        doc.fillColor('#4a5568').font('Helvetica').fontSize(10).text(`${i + 1}.  ${tip}`, 60, doc.y);
        doc.moveDown(0.4);
      });
    }
    if (itinerary.bestTime) {
      doc.moveDown(0.5).font('Helvetica-Bold').fontSize(10).fillColor('#87cfbe').text('Best Time to Visit: ', { continued: true })
         .font('Helvetica').fillColor('#4a5568').text(itinerary.bestTime);
    }

    // Footer
    const footerY = doc.page.height - 50;
    doc.moveTo(50, footerY - 10).lineTo(doc.page.width - 50, footerY - 10).strokeColor('#e2e8f0').lineWidth(1).stroke();
    doc.fillColor('#a0aec0').font('Helvetica').fontSize(9)
       .text(`Generated by WayEase  •  ${new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}`, 50, footerY, { align: 'center' });

    doc.end();
  } catch (err) {
    console.error('PDF error:', err);
    if (!res.headersSent) res.status(500).json({ error: 'Failed to generate PDF.' });
  }
});

module.exports = router;
